### ISSUE TITLE
Porting existing haxe games.

### ISSUE THREAD

**Issue by TyDevX** [Krismowo/3DSHaxe#2]
Is it possible to port existing haxe games like Ritz? If so what do I do with the project.xml and the main.hx from it?

**Comment by Krismowo** [comment]
if you mean porting existing haxeflixel games using it (which i believe you do) it would take a lot to port it as there isnt any way to use haxeflixel with 3dshaxe (not currently at least, though it is not planned)

**Comment by TyDevX** [comment]
Oh alright, thanks!
